#!/bin/sh

# Business program is identified by: src/main/cobol/sorlib/**.cbl
business_pgm=src/main/cobol/sorlib/pgm-to-test.cbl

# For every business program
# Test program is: src/test/cobol/testlib/<directory-to-source-code>/*.cbl
test_pgm=src/test/cobol/testlib/pgm-to-test/test-pgm.cbl

printf "Stage 0 - Instrumenting Code Coverage\n"
printf "===================================================\n"

# If running without code-coverage-precompiler, skip this step and point harness.sh directly at the program under test
mkdir coverage tmp
tmp_coverage_pgm=coverage/pgm-to-test.cbl
code-coverage-precompiler.sh $business_pgm $tmp_coverage_pgm &&

printf "\nStage 1 - Running the harness\n"
printf "===================================================\n"
./harness.sh $tmp_coverage_pgm $test_pgm &&

printf "\nStage 2 - Compile\n"
printf "===================================================\n"
cobc -x test-pgm-out.cbl -o testpgm -I "CUT" -I "tmp" &&

printf "\nStage 3 - Execute\n"
printf "===================================================\n"
./testpgm > Reports/dut-coverage-report.txt; cp CUT-RPTO "Reports/Unit Test Report.txt" &&

printf "\n"

grep -E -B 1 -A 1 '^\[(FAIL|ERROR|SKIP|DEBUG)\]' CUT-RPTO

printf "\n"

cat CUT-RPTO | tail -7

rm -r coverage tmp CUT-RPTO testpgm test-pgm-out.cbl